apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api
        imagePullPolicy: Never
        ports:
        - name: app-port
          containerPort: 3100
        resources:
          requests:
            memory: 256
            cpu: 100m
        envFrom:
          - configMapRef:
              name: env
        volumeMounts:
        - mountPath: "/data"
          name: data
        - mountPath: "/models"
          name: models
      volumes:
      - name: data
        hostPath:
          path: "/data"
      - name: models
        hostPath:
          path: "/models"

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: app-port
    port: 3100
    targetPort: app-port
