apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
        envFrom:
          - configMapRef:
              name: env
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redisdata
          mountPath: "/var/lib/redis/data"
      volumes:
      - name: redisdata
        persistentVolumeClaim:
          claimName: redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis 
  labels:
    app: redis
spec:
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379 
    name: redis
